# Generated by Django 5.1.7 on 2025-03-13 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(help_text='Введите номер без +7', max_length=11, validators=[django.core.validators.RegexValidator(message='Введите 10 цифр номера без +7', regex='^\\d{10}$')])),
                ('message', models.TextField()),
            ],
        ),
    ]
