# Generated by Django 5.1.7 on 2025-03-15 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='phone',
            field=models.CharField(help_text='Введите номер без +7', max_length=12, validators=[django.core.validators.RegexValidator(message='Введите 10 цифр номера без +7', regex='^\\d{10}$')]),
        ),
    ]
